server:
  port: ${PORT:18082}
  servlet:
    context-path: ${SERVLET_CONTEXT_PATH:/}
spring:
  application:
    name: mybatis-sample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:165.192.105.57}:${DB_PORT:30991}/${DB_NAME:mydb}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:P@ssw0rd$}
    #hikari:
    #  connection-test-query: 'SELECT 1  '
    #  connection-timeout: 5000
    #  maximum-pool-size: 30
    #  minimum-idle: 2
    #  validation-timeout: 1000
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
      
springdoc:
  packages-to-scan: com.example.rest
  paths-to-match: /**

  